# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eace7a90da04c20fe8290e86623daaeac61eb0ad4fe10577182f494ba6d91ab27e5ff2e85bbc610f465497f2283e5e75286f836aebb1115264cf01271060fb01

test:
  secret_key_base: 596b640c971d7ba5f8533274dd61743fd5b41e8307773c38a21f75f242dd20b2d6458610b53f6d69dfc55948588663fc0fe10d337a3f5cfdffc83ee6a77778b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
